name: 📰 Daily Global News Digest

on:
# schedule : kst 05:00, 17:00 daily
  schedule:
    - cron: "0 20 * * *"
    - cron: "0 08 * * *"
  workflow_dispatch:

# Node 20 감쇠 경고창을 없애고 깃허브 최신 표준(Node 24)으로 강제 작동시키는 설장
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  send-digest:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: 📦 Install dependencies
        run: pip install -r requirements.txt

      - name: 📰 Run news digest & send email
        env:
          EMAIL_USER: ${{ secrets.GMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAILS }}
        run: python scr/news_digest.py
